In [234]:
import pandas as pd

In [235]:
reg_2016 = pd.read_csv('2016_registration.csv')
reg_2020 = pd.read_csv('2020_registration.csv')
reg_both = pd.read_csv('registration_combined.csv')
district_2020 = pd.read_csv('nc_district_2020.csv')
district_2020.head()

,County,District,Total County Pop,Total District Pop,County Pop in District,Percent of County Pop in District,Percent of District Pop in County
0,Alamance,13.0,151131,733498,151131,100.0,20.604146
1,Alexander,5.0,37198,733499,37198,100.0,5.071309
2,Alleghany,5.0,11155,733499,11155,100.0,1.520793
3,Anson,9.0,26948,733499,26948,100.0,3.673897
4,Ashe,5.0,27281,733499,27281,100.0,3.719296

# 2020

In [236]:
# making the county names all uppercase to match 
district_2020['County'] = district_2020['County'].str.upper()

In [237]:
reg_2020
# adding non hispanic population
reg_2020['non_hispanic'] = reg_2020['total'] - reg_2020['hispanic']

column_to_move = reg_2020.pop('non_hispanic')  
reg_2020.insert(9, 'non_hispanic', column_to_move)
reg_2020

,index,total,female,male,white,black,american_indian/alaska_native,native_hawaiian/pacific_islander,hispanic,non_hispanic,...,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people,date
0,ALAMANCE,110926,55668,45447,71870,21888,274,7,4398,106528,...,39209,36271,34695,31,654,66,0,0,0,2020-11-03
1,ALEXANDER,24953,12071,11217,21634,938,37,1,352,24601,...,5105,11775,7940,3,108,22,0,0,0,2020-11-03
2,ALLEGHANY,7609,3647,3359,6739,76,8,0,188,7421,...,2156,2984,2429,4,34,2,0,0,0,2020-11-03
3,ANSON,16732,7542,6292,6709,6817,28,0,84,16648,...,10125,2867,3673,8,35,24,0,0,0,2020-11-03
4,ASHE,19545,9727,8723,17822,110,24,0,237,19308,...,4502,8875,6055,5,92,16,0,0,0,2020-11-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,WILKES,43934,21442,19339,38306,1619,48,0,748,43186,...,8229,23617,11875,11,180,22,0,0,0,2020-11-03
97,WILSON,57018,29789,23888,27397,23100,106,0,1435,55583,...,27794,14066,14889,15,219,35,0,0,0,2020-11-03
98,YADKIN,24725,12030,11031,21405,742,29,0,764,23961,...,3532,14061,6981,11,123,17,0,0,0,2020-11-03
99,YANCEY,14170,6927,6407,12879,79,21,0,91,14079,...,4435,5283,4379,5,61,7,0,0,0,2020-11-03
100,Totals,7361219,3650806,3102265,4700592,1518847,56094,372,227838,7133381,...,2623000,2231586,2452000,3619,46363,4651,0,0,0,2020-11-03

In [238]:
# merging on county
demo_2020 = pd.merge(district_2020, reg_2020, how='left', left_on = 'County', right_on ='index').drop(columns=['index', 'date'])
#demo_2020[demographics].multiply(demo_2020['Percent of District Pop in County']/100, axis=0)
demo_2020.head()

,County,District,Total County Pop,Total District Pop,County Pop in District,Percent of County Pop in District,Percent of District Pop in County,total,female,male,...,other_race,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people
0,ALAMANCE,13.0,151131,733498,151131,100.0,20.604146,110926,55668,45447,...,16887,39209,36271,34695,31,654,66,0,0,0
1,ALEXANDER,5.0,37198,733499,37198,100.0,5.071309,24953,12071,11217,...,2343,5105,11775,7940,3,108,22,0,0,0
2,ALLEGHANY,5.0,11155,733499,11155,100.0,1.520793,7609,3647,3359,...,786,2156,2984,2429,4,34,2,0,0,0
3,ANSON,9.0,26948,733499,26948,100.0,3.673897,16732,7542,6292,...,3178,10125,2867,3673,8,35,24,0,0,0
4,ASHE,5.0,27281,733499,27281,100.0,3.719296,19545,9727,8723,...,1589,4502,8875,6055,5,92,16,0,0,0

In [239]:
# column names of the demographic columns 
demo_groups = demo_2020.columns[7:].tolist()
demo_2020[demo_groups] = demo_2020[demo_groups].multiply(demo_2020['Percent of County Pop in District']/100, axis=0).round(0)
demo_2020.head(5)

,County,District,Total County Pop,Total District Pop,County Pop in District,Percent of County Pop in District,Percent of District Pop in County,total,female,male,...,other_race,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people
0,ALAMANCE,13.0,151131,733498,151131,100.0,20.604146,110926.0,55668.0,45447.0,...,16887.0,39209.0,36271.0,34695.0,31.0,654.0,66.0,0.0,0.0,0.0
1,ALEXANDER,5.0,37198,733499,37198,100.0,5.071309,24953.0,12071.0,11217.0,...,2343.0,5105.0,11775.0,7940.0,3.0,108.0,22.0,0.0,0.0,0.0
2,ALLEGHANY,5.0,11155,733499,11155,100.0,1.520793,7609.0,3647.0,3359.0,...,786.0,2156.0,2984.0,2429.0,4.0,34.0,2.0,0.0,0.0,0.0
3,ANSON,9.0,26948,733499,26948,100.0,3.673897,16732.0,7542.0,6292.0,...,3178.0,10125.0,2867.0,3673.0,8.0,35.0,24.0,0.0,0.0,0.0
4,ASHE,5.0,27281,733499,27281,100.0,3.719296,19545.0,9727.0,8723.0,...,1589.0,4502.0,8875.0,6055.0,5.0,92.0,16.0,0.0,0.0,0.0

In [240]:
# column which contains list of counties for each district
district_counties = demo_2020.groupby('District')['County'].apply(lambda x: list(x.unique())).reset_index()
district_counties

    District                                             County
0        1.0  [BERTIE, EDGECOMBE, GATES, GREENE, HALIFAX, HE...
1        2.0                                             [WAKE]
2        3.0  [BEAUFORT, CAMDEN, CARTERET, CHOWAN, CRAVEN, C...
3        4.0  [CHATHAM, DURHAM, FRANKLIN, GRANVILLE, ORANGE,...
4        5.0  [ALEXANDER, ALLEGHANY, ASHE, BURKE, CALDWELL, ...
5        6.0                                [FORSYTH, GUILFORD]
6        7.0  [BLADEN, BRUNSWICK, COLUMBUS, HARNETT, JOHNSTO...
7        8.0  [CABARRUS, CUMBERLAND, HARNETT, LEE, MONTGOMER...
8        9.0  [ANSON, HOKE, MECKLENBURG, MOORE, RICHMOND, RO...
9       10.0  [CATAWBA, FORSYTH, IREDELL, LINCOLN, ROCKINGHA...
10      11.0  [AVERY, BUNCOMBE, CHEROKEE, CLAY, GRAHAM, HAYW...
11      12.0                                      [MECKLENBURG]
12      13.0  [ALAMANCE, CASWELL, CHATHAM, DAVIDSON, DAVIE, ...

In [241]:
# getting sums across demographic fielst
demo_drop = demo_2020.drop(['County', 'Total County Pop', 'Total District Pop','Percent of County Pop in District', 'Percent of District Pop in County'], axis = 1)
districts_totaled = demo_drop.groupby('District').sum()
districts_totaled

,County Pop in District,total,female,male,white,black,american_indian/alaska_native,native_hawaiian/pacific_islander,hispanic,non_hispanic,other_race,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people
District,,,,,,,,,,,,,,,,,,,,
1.0,733498,491721.0,254213.0,206173.0,231383.0,207465.0,2727.0,10.0,9438.0,482284.0,50135.0,252138.0,114022.0,123106.0,162.0,2021.0,274.0,0.0,0.0,0.0
2.0,733499,646799.0,307578.0,268634.0,391624.0,117602.0,1540.0,22.0,23587.0,623212.0,136011.0,237320.0,153747.0,249967.0,344.0,5051.0,370.0,0.0,0.0,0.0
3.0,733499,513402.0,257277.0,219164.0,349699.0,102902.0,1119.0,39.0,13149.0,500253.0,59643.0,159000.0,177306.0,172800.0,244.0,3662.0,389.0,0.0,0.0,0.0
4.0,733499,631778.0,305447.0,254979.0,357848.0,145546.0,1513.0,33.0,22501.0,609276.0,126839.0,289072.0,112428.0,225871.0,343.0,3788.0,275.0,0.0,0.0,0.0
5.0,733499,514322.0,253354.0,222047.0,403379.0,51897.0,840.0,7.0,10256.0,504066.0,58199.0,134891.0,211573.0,164095.0,235.0,3152.0,376.0,0.0,0.0,0.0
6.0,733498,573832.0,293869.0,236800.0,309472.0,176885.0,1385.0,19.0,19009.0,554823.0,86071.0,243303.0,147832.0,178697.0,315.0,3374.0,311.0,0.0,0.0,0.0
7.0,733499,611479.0,300993.0,258717.0,432801.0,94242.0,3331.0,33.0,16278.0,595201.0,81072.0,185311.0,215015.0,206446.0,269.0,4016.0,422.0,0.0,0.0,0.0
8.0,733498,545001.0,266796.0,222596.0,302991.0,143289.0,3432.0,70.0,24888.0,520114.0,95220.0,191429.0,169869.0,179129.0,244.0,3869.0,460.0,0.0,0.0,0.0
9.0,733499,553098.0,277698.0,235532.0,306322.0,131629.0,32027.0,40.0,19994.0,533103.0,83080.0,212364.0,156243.0,180656.0,247.0,3188.0,400.0,0.0,0.0,0.0
10.0,733499,537100.0,266082.0,233779.0,407139.0,61322.0,826.0,10.0,15086.0,522014.0,67803.0,135913.0,224768.0,172973.0,200.0,2891.0,355.0,0.0,0.0,0.0
11.0,733499,590256.0,295489.0,257267.0,505987.0,19149.0,4372.0,40.0,9622.0,580634.0,60708.0,170632.0,195039.0,219858.0,456.0,3947.0,324.0,0.0,0.0,0.0
12.0,733499,631927.0,315846.0,264051.0,320656.0,195488.0,1690.0,26.0,29812.0,602115.0,114067.0,272268.0,136023.0,218298.0,369.0,4618.0,351.0,0.0,0.0,0.0
13.0,733498,520504.0,256164.0,222526.0,381291.0,71431.0,1292.0,23.0,14218.0,506286.0,66466.0,139359.0,217721.0,160104.0,191.0,2786.0,344.0,0.0,0.0,0.0

In [242]:
district_demo_2020 = pd.merge(districts_totaled, district_counties, how='left', on= 'District')
district_demo_2020.rename(columns={'County Pop in District': 'district_pop', 'total':'n_reg_voters'}, inplace=True)

district_demo_2020

,District,district_pop,n_reg_voters,female,male,white,black,american_indian/alaska_native,native_hawaiian/pacific_islander,hispanic,...,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people,County
0,1.0,733498,491721.0,254213.0,206173.0,231383.0,207465.0,2727.0,10.0,9438.0,...,252138.0,114022.0,123106.0,162.0,2021.0,274.0,0.0,0.0,0.0,"[BERTIE, EDGECOMBE, GATES, GREENE, HALIFAX, HE..."
1,2.0,733499,646799.0,307578.0,268634.0,391624.0,117602.0,1540.0,22.0,23587.0,...,237320.0,153747.0,249967.0,344.0,5051.0,370.0,0.0,0.0,0.0,[WAKE]
2,3.0,733499,513402.0,257277.0,219164.0,349699.0,102902.0,1119.0,39.0,13149.0,...,159000.0,177306.0,172800.0,244.0,3662.0,389.0,0.0,0.0,0.0,"[BEAUFORT, CAMDEN, CARTERET, CHOWAN, CRAVEN, C..."
3,4.0,733499,631778.0,305447.0,254979.0,357848.0,145546.0,1513.0,33.0,22501.0,...,289072.0,112428.0,225871.0,343.0,3788.0,275.0,0.0,0.0,0.0,"[CHATHAM, DURHAM, FRANKLIN, GRANVILLE, ORANGE,..."
4,5.0,733499,514322.0,253354.0,222047.0,403379.0,51897.0,840.0,7.0,10256.0,...,134891.0,211573.0,164095.0,235.0,3152.0,376.0,0.0,0.0,0.0,"[ALEXANDER, ALLEGHANY, ASHE, BURKE, CALDWELL, ..."
5,6.0,733498,573832.0,293869.0,236800.0,309472.0,176885.0,1385.0,19.0,19009.0,...,243303.0,147832.0,178697.0,315.0,3374.0,311.0,0.0,0.0,0.0,"[FORSYTH, GUILFORD]"
6,7.0,733499,611479.0,300993.0,258717.0,432801.0,94242.0,3331.0,33.0,16278.0,...,185311.0,215015.0,206446.0,269.0,4016.0,422.0,0.0,0.0,0.0,"[BLADEN, BRUNSWICK, COLUMBUS, HARNETT, JOHNSTO..."
7,8.0,733498,545001.0,266796.0,222596.0,302991.0,143289.0,3432.0,70.0,24888.0,...,191429.0,169869.0,179129.0,244.0,3869.0,460.0,0.0,0.0,0.0,"[CABARRUS, CUMBERLAND, HARNETT, LEE, MONTGOMER..."
8,9.0,733499,553098.0,277698.0,235532.0,306322.0,131629.0,32027.0,40.0,19994.0,...,212364.0,156243.0,180656.0,247.0,3188.0,400.0,0.0,0.0,0.0,"[ANSON, HOKE, MECKLENBURG, MOORE, RICHMOND, RO..."
9,10.0,733499,537100.0,266082.0,233779.0,407139.0,61322.0,826.0,10.0,15086.0,...,135913.0,224768.0,172973.0,200.0,2891.0,355.0,0.0,0.0,0.0,"[CATAWBA, FORSYTH, IREDELL, LINCOLN, ROCKINGHA..."
10,11.0,733499,590256.0,295489.0,257267.0,505987.0,19149.0,4372.0,40.0,9622.0,...,170632.0,195039.0,219858.0,456.0,3947.0,324.0,0.0,0.0,0.0,"[AVERY, BUNCOMBE, CHEROKEE, CLAY, GRAHAM, HAYW..."
11,12.0,733499,631927.0,315846.0,264051.0,320656.0,195488.0,1690.0,26.0,29812.0,...,272268.0,136023.0,218298.0,369.0,4618.0,351.0,0.0,0.0,0.0,[MECKLENBURG]
12,13.0,733498,520504.0,256164.0,222526.0,381291.0,71431.0,1292.0,23.0,14218.0,...,139359.0,217721.0,160104.0,191.0,2786.0,344.0,0.0,0.0,0.0,"[ALAMANCE, CASWELL, CHATHAM, DAVIDSON, DAVIE, ..."

In [243]:
demo_groups

['total',
 'female',
 'male',
 'white',
 'black',
 'american_indian/alaska_native',
 'native_hawaiian/pacific_islander',
 'hispanic',
 'non_hispanic',
 'other_race',
 'democrat',
 'republican',
 'unaffiliated',
 'green',
 'libertarian',
 'constitution',
 'justice_for_all',
 'no_labels',
 'we_the_people']

In [244]:

# adding column for percentage of each demographic over n_reg voters 
for col in demo_groups[1:]:
    district_demo_2020[f'{col}_percent_of_reg_voters'] = district_demo_2020[col] / district_demo_2020['n_reg_voters']

for col in demo_groups[1:]:
    district_demo_2020[f'{col}_percent_of_pop'] = district_demo_2020[col] / district_demo_2020['district_pop']

district_demo_2020

,District,district_pop,n_reg_voters,female,male,white,black,american_indian/alaska_native,native_hawaiian/pacific_islander,hispanic,...,other_race_percent_of_pop,democrat_percent_of_pop,republican_percent_of_pop,unaffiliated_percent_of_pop,green_percent_of_pop,libertarian_percent_of_pop,constitution_percent_of_pop,justice_for_all_percent_of_pop,no_labels_percent_of_pop,we_the_people_percent_of_pop
0,1.0,733498,491721.0,254213.0,206173.0,231383.0,207465.0,2727.0,10.0,9438.0,...,0.068351,0.343747,0.155450,0.167834,0.000221,0.002755,0.000374,0.0,0.0,0.0
1,2.0,733499,646799.0,307578.0,268634.0,391624.0,117602.0,1540.0,22.0,23587.0,...,0.185428,0.323545,0.209608,0.340787,0.000469,0.006886,0.000504,0.0,0.0,0.0
2,3.0,733499,513402.0,257277.0,219164.0,349699.0,102902.0,1119.0,39.0,13149.0,...,0.081313,0.216769,0.241726,0.235583,0.000333,0.004993,0.000530,0.0,0.0,0.0
3,4.0,733499,631778.0,305447.0,254979.0,357848.0,145546.0,1513.0,33.0,22501.0,...,0.172923,0.394100,0.153276,0.307936,0.000468,0.005164,0.000375,0.0,0.0,0.0
4,5.0,733499,514322.0,253354.0,222047.0,403379.0,51897.0,840.0,7.0,10256.0,...,0.079344,0.183901,0.288443,0.223715,0.000320,0.004297,0.000513,0.0,0.0,0.0
5,6.0,733498,573832.0,293869.0,236800.0,309472.0,176885.0,1385.0,19.0,19009.0,...,0.117343,0.331702,0.201544,0.243623,0.000429,0.004600,0.000424,0.0,0.0,0.0
6,7.0,733499,611479.0,300993.0,258717.0,432801.0,94242.0,3331.0,33.0,16278.0,...,0.110528,0.252640,0.293136,0.281454,0.000367,0.005475,0.000575,0.0,0.0,0.0
7,8.0,733498,545001.0,266796.0,222596.0,302991.0,143289.0,3432.0,70.0,24888.0,...,0.129816,0.260981,0.231588,0.244212,0.000333,0.005275,0.000627,0.0,0.0,0.0
8,9.0,733499,553098.0,277698.0,235532.0,306322.0,131629.0,32027.0,40.0,19994.0,...,0.113265,0.289522,0.213011,0.246293,0.000337,0.004346,0.000545,0.0,0.0,0.0
9,10.0,733499,537100.0,266082.0,233779.0,407139.0,61322.0,826.0,10.0,15086.0,...,0.092438,0.185294,0.306433,0.235819,0.000273,0.003941,0.000484,0.0,0.0,0.0
10,11.0,733499,590256.0,295489.0,257267.0,505987.0,19149.0,4372.0,40.0,9622.0,...,0.082765,0.232627,0.265902,0.299739,0.000622,0.005381,0.000442,0.0,0.0,0.0
11,12.0,733499,631927.0,315846.0,264051.0,320656.0,195488.0,1690.0,26.0,29812.0,...,0.155511,0.371191,0.185444,0.297612,0.000503,0.006296,0.000479,0.0,0.0,0.0
12,13.0,733498,520504.0,256164.0,222526.0,381291.0,71431.0,1292.0,23.0,14218.0,...,0.090615,0.189992,0.296826,0.218275,0.000260,0.003798,0.000469,0.0,0.0,0.0

In [245]:
district_demo_2020.to_csv('district_demo_2020.csv', index=False)

# 2016

In [246]:
district_2016 = pd.read_csv('nc_pop_2016.csv')
district_2016['County'] = district_2016['County'].str.upper()
# turning country district pop into a int since it will be used later in a calculation 
district_2016['County District Pop'] = district_2016['County District Pop'].str.replace(",", "").astype(float)

district_2016.head()

,County,District,County Pop,District Pop,County District Pop,Percent County in District,Percent District in County
0,ALAMANCE,6.0,"151,131.00","733,498.00",151131.0,100.0,20.60
1,ALEXANDER,5.0,"37,198.00","733,499.00",37198.0,100.0,5.07
2,ALLEGHANY,5.0,"11,155.00","733,499.00",11155.0,100.0,1.52
3,ANSON,9.0,"26,948.00","733,498.00",26948.0,100.0,3.67
4,ASHE,5.0,"27,281.00","733,499.00",27281.0,100.0,3.72

In [247]:
reg_2016['non_hispanic'] = reg_2016['total'] - reg_2016['hispanic']

column_to_move = reg_2016.pop('non_hispanic')  
reg_2016.insert(9, 'non_hispanic', column_to_move)
reg_2016

,index,total,female,male,white,black,american_indian/alaska_native,native_hawaiian/pacific_islander,hispanic,non_hispanic,...,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people,date
0,ALAMANCE,101136,54471,44140,72449,20715,273,0,2770,98366,...,39529,33130,28037,0,440,0,0,0,0,2016-11-08
1,ALEXANDER,24429,12541,11651,22683,1006,33,0,232,24197,...,6553,10749,7056,0,71,0,0,0,0,2016-11-08
2,ALLEGHANY,7470,3903,3495,7132,83,12,0,166,7304,...,2813,2557,2064,0,36,0,0,0,0,2016-11-08
3,ANSON,17416,8311,7013,7514,7682,37,0,58,17358,...,11939,2456,3002,0,19,0,0,0,0,2016-11-08
4,ASHE,19044,9962,8934,18479,104,22,0,177,18867,...,5668,8060,5251,0,65,0,0,0,0,2016-11-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,WILKES,43012,22438,20025,40146,1740,36,0,591,42421,...,10353,22089,10451,0,119,0,0,0,0,2016-11-08
97,WILSON,56578,30693,24849,29565,23620,97,0,989,55589,...,30222,13932,12289,0,135,0,0,0,0,2016-11-08
98,YADKIN,24142,12516,11286,22523,760,34,0,526,23616,...,4303,13409,6360,0,70,0,0,0,0,2016-11-08
99,YANCEY,13962,7207,6586,13580,87,22,0,67,13895,...,5293,4918,3709,0,42,0,0,0,0,2016-11-08
100,Totals,6918150,3663903,3096349,4799695,1536117,56634,0,166964,6751186,...,2733188,2086942,2065687,0,32333,0,0,0,0,2016-11-08

In [248]:
# merging on county
demo_2016 = pd.merge(district_2016, reg_2016, how='left', left_on = 'County', right_on ='index').drop(columns=['index', 'date'])
demo_2016.head(10)

,County,District,County Pop,District Pop,County District Pop,Percent County in District,Percent District in County,total,female,male,...,other_race,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people
0,ALAMANCE,6.0,"151,131.00","733,498.00",151131.0,100.00,20.60,101136,54471,44140,...,7699,39529,33130,28037,0,440,0,0,0,0
1,ALEXANDER,5.0,"37,198.00","733,499.00",37198.0,100.00,5.07,24429,12541,11651,...,707,6553,10749,7056,0,71,0,0,0,0
2,ALLEGHANY,5.0,"11,155.00","733,499.00",11155.0,100.00,1.52,7470,3903,3495,...,243,2813,2557,2064,0,36,0,0,0,0
3,ANSON,9.0,"26,948.00","733,498.00",26948.0,100.00,3.67,17416,8311,7013,...,2183,11939,2456,3002,0,19,0,0,0,0
4,ASHE,5.0,"27,281.00","733,499.00",27281.0,100.00,3.72,19044,9962,8934,...,439,5668,8060,5251,0,65,0,0,0,0
5,AVERY,5.0,"17,797.00","733,499.00",17797.0,100.00,2.43,11959,6342,5527,...,296,1493,7029,3388,0,49,0,0,0,0
6,BEAUFORT,3.0,"47,759.00","733,498.00",47759.0,100.00,6.51,33322,17679,14843,...,1375,13896,10743,8585,0,98,0,0,0,0
7,BERTIE,1.0,"21,282.00","733,499.00",21282.0,100.00,2.90,14248,7696,6158,...,586,10309,1541,2379,0,19,0,0,0,0
8,BLADEN,7.0,"35,190.00","733,499.00",8981.0,25.52,1.22,23086,12407,10529,...,703,13713,3462,5878,0,33,0,0,0,0
9,BLADEN,9.0,"35,190.00","733,498.00",26209.0,74.48,3.57,23086,12407,10529,...,703,13713,3462,5878,0,33,0,0,0,0

In [249]:
# column names of the demographic columns 
demo_groups = demo_2016.columns[7:].tolist()
demo_2016[demo_groups] = demo_2016[demo_groups].multiply(demo_2016['Percent County in District']/100, axis=0).round(0)
demo_2016.head(5)

,County,District,County Pop,District Pop,County District Pop,Percent County in District,Percent District in County,total,female,male,...,other_race,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people
0,ALAMANCE,6.0,"151,131.00","733,498.00",151131.0,100.0,20.60,101136.0,54471.0,44140.0,...,7699.0,39529.0,33130.0,28037.0,0.0,440.0,0.0,0.0,0.0,0.0
1,ALEXANDER,5.0,"37,198.00","733,499.00",37198.0,100.0,5.07,24429.0,12541.0,11651.0,...,707.0,6553.0,10749.0,7056.0,0.0,71.0,0.0,0.0,0.0,0.0
2,ALLEGHANY,5.0,"11,155.00","733,499.00",11155.0,100.0,1.52,7470.0,3903.0,3495.0,...,243.0,2813.0,2557.0,2064.0,0.0,36.0,0.0,0.0,0.0,0.0
3,ANSON,9.0,"26,948.00","733,498.00",26948.0,100.0,3.67,17416.0,8311.0,7013.0,...,2183.0,11939.0,2456.0,3002.0,0.0,19.0,0.0,0.0,0.0,0.0
4,ASHE,5.0,"27,281.00","733,499.00",27281.0,100.0,3.72,19044.0,9962.0,8934.0,...,439.0,5668.0,8060.0,5251.0,0.0,65.0,0.0,0.0,0.0,0.0

In [250]:
# column which contains list of counties for each district
district_counties = demo_2016.groupby('District')['County'].apply(lambda x: list(x.unique())).reset_index()
district_counties

    District                                             County
0        1.0  [BERTIE, DURHAM, EDGECOMBE, GATES, GRANVILLE, ...
1        2.0  [FRANKLIN, HARNETT, JOHNSTON, NASH, WAKE, WILSON]
2        3.0  [BEAUFORT, CAMDEN, CARTERET, CHOWAN, CRAVEN, C...
3        4.0                             [DURHAM, ORANGE, WAKE]
4        5.0  [ALEXANDER, ALLEGHANY, ASHE, AVERY, CATAWBA, F...
5        6.0  [ALAMANCE, CASWELL, CHATHAM, GUILFORD, LEE, PE...
6        7.0  [BLADEN, BRUNSWICK, COLUMBUS, DUPLIN, JOHNSTON...
7        8.0  [CABARRUS, CUMBERLAND, HOKE, MONTGOMERY, MOORE...
8        9.0  [ANSON, BLADEN, CUMBERLAND, MECKLENBURG, RICHM...
9       10.0  [BUNCOMBE, CATAWBA, CLEVELAND, GASTON, IREDELL...
10      11.0  [BUNCOMBE, BURKE, CALDWELL, CHEROKEE, CLAY, GR...
11      12.0                                      [MECKLENBURG]
12      13.0        [DAVIDSON, DAVIE, GUILFORD, IREDELL, ROWAN]

In [251]:
demo_2016[demo_2016["County"] == 'MECKLENBURG']

,County,District,County Pop,District Pop,County District Pop,Percent County in District,Percent District in County,total,female,male,...,other_race,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people
67,MECKLENBURG,9.0,"919,628.00","733,498.00",186130.0,20.24,25.38,143834.0,76935.0,63671.0,...,15401.0,64100.0,34921.0,44027.0,0.0,787.0,0.0,0.0,0.0,0.0
68,MECKLENBURG,12.0,"919,628.00","733,498.00",733498.0,79.76,100.00,566809.0,303180.0,250907.0,...,60691.0,252598.0,137613.0,173496.0,0.0,3101.0,0.0,0.0,0.0,0.0

In [252]:
# getting sums across demographic fielst
demo_drop = demo_2016.drop(['County', 'County Pop', 'District Pop','Percent County in District', 'Percent District in County'], axis = 1)
districts_totaled = demo_drop.groupby('District').sum()
districts_totaled

,County District Pop,total,female,male,white,black,american_indian/alaska_native,native_hawaiian/pacific_islander,hispanic,non_hispanic,other_race,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people
District,,,,,,,,,,,,,,,,,,,,
1.0,733499.0,545947.0,294172.0,236525.0,264577.0,236489.0,2888.0,0.0,10535.0,535412.0,41993.0,321321.0,88899.0,133808.0,0.0,1919.0,0.0,0.0,0.0,0.0
2.0,733499.0,537196.0,280527.0,241031.0,356535.0,126069.0,1851.0,0.0,15185.0,522012.0,52742.0,211345.0,161075.0,161959.0,0.0,2819.0,0.0,0.0,0.0,0.0
3.0,733498.0,507737.0,269931.0,228322.0,362890.0,115425.0,1146.0,0.0,10040.0,497697.0,28276.0,190504.0,159116.0,155544.0,0.0,2572.0,0.0,0.0,0.0,0.0
4.0,733499.0,588136.0,302299.0,260477.0,393852.0,111923.0,1500.0,0.0,17982.0,570153.0,80861.0,236477.0,140501.0,207661.0,0.0,3497.0,0.0,0.0,0.0,0.0
5.0,733499.0,516137.0,273548.0,232501.0,406570.0,79319.0,897.0,0.0,11737.0,504399.0,29350.0,175126.0,192190.0,146456.0,0.0,2365.0,0.0,0.0,0.0,0.0
6.0,733498.0,506340.0,271154.0,226605.0,363982.0,107979.0,1411.0,0.0,12120.0,494221.0,32968.0,196457.0,165819.0,141985.0,0.0,2079.0,0.0,0.0,0.0,0.0
7.0,733499.0,535322.0,281912.0,239197.0,395563.0,105173.0,2813.0,0.0,10658.0,524663.0,31772.0,198724.0,174647.0,159510.0,0.0,2440.0,0.0,0.0,0.0,0.0
8.0,733499.0,510518.0,270596.0,227386.0,334941.0,129223.0,4928.0,0.0,16268.0,494248.0,41427.0,187080.0,167850.0,153272.0,0.0,2316.0,0.0,0.0,0.0,0.0
9.0,733498.0,509478.0,271094.0,227382.0,295347.0,141980.0,30512.0,0.0,14954.0,494526.0,41638.0,231279.0,134092.0,142128.0,0.0,1980.0,0.0,0.0,0.0,0.0
10.0,733499.0,519321.0,274985.0,235120.0,429253.0,60863.0,981.0,0.0,8980.0,510341.0,28225.0,171828.0,187556.0,157650.0,0.0,2286.0,0.0,0.0,0.0,0.0
11.0,733499.0,548166.0,288202.0,252207.0,501231.0,18861.0,4801.0,0.0,6565.0,541601.0,23273.0,173521.0,188182.0,183713.0,0.0,2750.0,0.0,0.0,0.0,0.0
12.0,733498.0,566809.0,303180.0,250907.0,318026.0,186468.0,1624.0,0.0,21767.0,545042.0,60691.0,252598.0,137613.0,173496.0,0.0,3101.0,0.0,0.0,0.0,0.0
13.0,733499.0,527043.0,282303.0,238689.0,376928.0,116345.0,1282.0,0.0,10173.0,516871.0,32488.0,186928.0,189402.0,148505.0,0.0,2209.0,0.0,0.0,0.0,0.0

In [253]:
district_demo_2016 = pd.merge(districts_totaled, district_counties, how='left', on= 'District')
district_demo_2016.rename(columns={'County District Pop': 'district_pop', 'total':'n_reg_voters'}, inplace=True)

district_demo_2016

,District,district_pop,n_reg_voters,female,male,white,black,american_indian/alaska_native,native_hawaiian/pacific_islander,hispanic,...,democrat,republican,unaffiliated,green,libertarian,constitution,justice_for_all,no_labels,we_the_people,County
0,1.0,733499.0,545947.0,294172.0,236525.0,264577.0,236489.0,2888.0,0.0,10535.0,...,321321.0,88899.0,133808.0,0.0,1919.0,0.0,0.0,0.0,0.0,"[BERTIE, DURHAM, EDGECOMBE, GATES, GRANVILLE, ..."
1,2.0,733499.0,537196.0,280527.0,241031.0,356535.0,126069.0,1851.0,0.0,15185.0,...,211345.0,161075.0,161959.0,0.0,2819.0,0.0,0.0,0.0,0.0,"[FRANKLIN, HARNETT, JOHNSTON, NASH, WAKE, WILSON]"
2,3.0,733498.0,507737.0,269931.0,228322.0,362890.0,115425.0,1146.0,0.0,10040.0,...,190504.0,159116.0,155544.0,0.0,2572.0,0.0,0.0,0.0,0.0,"[BEAUFORT, CAMDEN, CARTERET, CHOWAN, CRAVEN, C..."
3,4.0,733499.0,588136.0,302299.0,260477.0,393852.0,111923.0,1500.0,0.0,17982.0,...,236477.0,140501.0,207661.0,0.0,3497.0,0.0,0.0,0.0,0.0,"[DURHAM, ORANGE, WAKE]"
4,5.0,733499.0,516137.0,273548.0,232501.0,406570.0,79319.0,897.0,0.0,11737.0,...,175126.0,192190.0,146456.0,0.0,2365.0,0.0,0.0,0.0,0.0,"[ALEXANDER, ALLEGHANY, ASHE, AVERY, CATAWBA, F..."
5,6.0,733498.0,506340.0,271154.0,226605.0,363982.0,107979.0,1411.0,0.0,12120.0,...,196457.0,165819.0,141985.0,0.0,2079.0,0.0,0.0,0.0,0.0,"[ALAMANCE, CASWELL, CHATHAM, GUILFORD, LEE, PE..."
6,7.0,733499.0,535322.0,281912.0,239197.0,395563.0,105173.0,2813.0,0.0,10658.0,...,198724.0,174647.0,159510.0,0.0,2440.0,0.0,0.0,0.0,0.0,"[BLADEN, BRUNSWICK, COLUMBUS, DUPLIN, JOHNSTON..."
7,8.0,733499.0,510518.0,270596.0,227386.0,334941.0,129223.0,4928.0,0.0,16268.0,...,187080.0,167850.0,153272.0,0.0,2316.0,0.0,0.0,0.0,0.0,"[CABARRUS, CUMBERLAND, HOKE, MONTGOMERY, MOORE..."
8,9.0,733498.0,509478.0,271094.0,227382.0,295347.0,141980.0,30512.0,0.0,14954.0,...,231279.0,134092.0,142128.0,0.0,1980.0,0.0,0.0,0.0,0.0,"[ANSON, BLADEN, CUMBERLAND, MECKLENBURG, RICHM..."
9,10.0,733499.0,519321.0,274985.0,235120.0,429253.0,60863.0,981.0,0.0,8980.0,...,171828.0,187556.0,157650.0,0.0,2286.0,0.0,0.0,0.0,0.0,"[BUNCOMBE, CATAWBA, CLEVELAND, GASTON, IREDELL..."
10,11.0,733499.0,548166.0,288202.0,252207.0,501231.0,18861.0,4801.0,0.0,6565.0,...,173521.0,188182.0,183713.0,0.0,2750.0,0.0,0.0,0.0,0.0,"[BUNCOMBE, BURKE, CALDWELL, CHEROKEE, CLAY, GR..."
11,12.0,733498.0,566809.0,303180.0,250907.0,318026.0,186468.0,1624.0,0.0,21767.0,...,252598.0,137613.0,173496.0,0.0,3101.0,0.0,0.0,0.0,0.0,[MECKLENBURG]
12,13.0,733499.0,527043.0,282303.0,238689.0,376928.0,116345.0,1282.0,0.0,10173.0,...,186928.0,189402.0,148505.0,0.0,2209.0,0.0,0.0,0.0,0.0,"[DAVIDSON, DAVIE, GUILFORD, IREDELL, ROWAN]"

In [254]:
# adding column for percentage of each demographic over n_reg voters 
for col in demo_groups[1:]:
    district_demo_2016[f'{col}_percent_of_reg_voters'] = district_demo_2016[col] / district_demo_2016['n_reg_voters']

for col in demo_groups[1:]:
    district_demo_2016[f'{col}_percent_of_pop'] = district_demo_2016[col] / district_demo_2016['district_pop']

district_demo_2016

,District,district_pop,n_reg_voters,female,male,white,black,american_indian/alaska_native,native_hawaiian/pacific_islander,hispanic,...,other_race_percent_of_pop,democrat_percent_of_pop,republican_percent_of_pop,unaffiliated_percent_of_pop,green_percent_of_pop,libertarian_percent_of_pop,constitution_percent_of_pop,justice_for_all_percent_of_pop,no_labels_percent_of_pop,we_the_people_percent_of_pop
0,1.0,733499.0,545947.0,294172.0,236525.0,264577.0,236489.0,2888.0,0.0,10535.0,...,0.057250,0.438066,0.121199,0.182424,0.0,0.002616,0.0,0.0,0.0,0.0
1,2.0,733499.0,537196.0,280527.0,241031.0,356535.0,126069.0,1851.0,0.0,15185.0,...,0.071905,0.288133,0.219598,0.220803,0.0,0.003843,0.0,0.0,0.0,0.0
2,3.0,733498.0,507737.0,269931.0,228322.0,362890.0,115425.0,1146.0,0.0,10040.0,...,0.038550,0.259720,0.216928,0.212058,0.0,0.003506,0.0,0.0,0.0,0.0
3,4.0,733499.0,588136.0,302299.0,260477.0,393852.0,111923.0,1500.0,0.0,17982.0,...,0.110240,0.322396,0.191549,0.283110,0.0,0.004768,0.0,0.0,0.0,0.0
4,5.0,733499.0,516137.0,273548.0,232501.0,406570.0,79319.0,897.0,0.0,11737.0,...,0.040014,0.238754,0.262018,0.199668,0.0,0.003224,0.0,0.0,0.0,0.0
5,6.0,733498.0,506340.0,271154.0,226605.0,363982.0,107979.0,1411.0,0.0,12120.0,...,0.044946,0.267836,0.226066,0.193572,0.0,0.002834,0.0,0.0,0.0,0.0
6,7.0,733499.0,535322.0,281912.0,239197.0,395563.0,105173.0,2813.0,0.0,10658.0,...,0.043316,0.270926,0.238101,0.217465,0.0,0.003327,0.0,0.0,0.0,0.0
7,8.0,733499.0,510518.0,270596.0,227386.0,334941.0,129223.0,4928.0,0.0,16268.0,...,0.056479,0.255051,0.228835,0.208960,0.0,0.003157,0.0,0.0,0.0,0.0
8,9.0,733498.0,509478.0,271094.0,227382.0,295347.0,141980.0,30512.0,0.0,14954.0,...,0.056766,0.315310,0.182812,0.193767,0.0,0.002699,0.0,0.0,0.0,0.0
9,10.0,733499.0,519321.0,274985.0,235120.0,429253.0,60863.0,981.0,0.0,8980.0,...,0.038480,0.234258,0.255700,0.214929,0.0,0.003117,0.0,0.0,0.0,0.0
10,11.0,733499.0,548166.0,288202.0,252207.0,501231.0,18861.0,4801.0,0.0,6565.0,...,0.031729,0.236566,0.256554,0.250461,0.0,0.003749,0.0,0.0,0.0,0.0
11,12.0,733498.0,566809.0,303180.0,250907.0,318026.0,186468.0,1624.0,0.0,21767.0,...,0.082742,0.344374,0.187612,0.236532,0.0,0.004228,0.0,0.0,0.0,0.0
12,13.0,733499.0,527043.0,282303.0,238689.0,376928.0,116345.0,1282.0,0.0,10173.0,...,0.044292,0.254844,0.258217,0.202461,0.0,0.003012,0.0,0.0,0.0,0.0

In [264]:
district_demo_2016.to_csv('district_demo_2016.csv', index=False)

In [260]:
district_demo_2016['white_percent_of_reg_voters']

0     0.484620
1     0.663696
2     0.714720
3     0.669661
4     0.787717
5     0.718849
6     0.738925
7     0.656081
8     0.579705
9     0.826566
10    0.914378
11    0.561081
12    0.715175
Name: white_percent_of_reg_voters, dtype: float64

In [275]:
district_demo_2020['black_percent_of_reg_voters']

0     0.421916
1     0.181822
2     0.200432
3     0.230375
4     0.100904
5     0.308252
6     0.154121
7     0.262915
8     0.237985
9     0.114172
10    0.032442
11    0.309352
12    0.137234
Name: black_percent_of_reg_voters, dtype: float64

In [286]:
district_demo_2016['black_percent_of_pop']-

0    -2.677588
1    -2.828127
2    -2.842638
3    -2.847412
4    -2.891862
5    -2.852789
6    -2.856615
7    -2.823827
8    -2.806434
9    -2.917024
10   -2.974286
11   -2.745783
12   -2.841384
Name: black_percent_of_pop, dtype: float64

In [285]:
district_demo_2020['black_percent_of_pop']

0     0.282843
1     0.160330
2     0.140289
3     0.198427
4     0.070753
5     0.241153
6     0.128483
7     0.195350
8     0.179454
9     0.083602
10    0.026106
11    0.266514
12    0.097384
Name: black_percent_of_pop, dtype: float64

In [290]:
(district_demo_2016['black_percent_of_reg_voters'] - (district_demo_2016['black'].sum()/district_demo_2016['district_pop'].sum())).sum()

0.7877839207986488

In [291]:
(district_demo_2020['black_percent_of_reg_voters'] - (district_demo_2020['black'].sum()/district_demo_2020['district_pop'].sum())).sum()

0.6212345842915429

In [274]:
district_demo_2016['democrat_percent_of_reg_voters']

0     0.588557
1     0.393423
2     0.375202
3     0.402079
4     0.339301
5     0.387994
6     0.371223
7     0.366451
8     0.453953
9     0.330871
10    0.316548
11    0.445649
12    0.354673
Name: democrat_percent_of_reg_voters, dtype: float64

In [266]:
district_demo_2020['democrat_percent_of_reg_voters']

0     0.512766
1     0.366915
2     0.309699
3     0.457553
4     0.262270
5     0.423997
6     0.303054
7     0.351245
8     0.383954
9     0.253050
10    0.289081
11    0.430854
12    0.267739
Name: democrat_percent_of_reg_voters, dtype: float64

In [282]:
district_demo_2016['black'].sum()/district_demo_2016['district_pop'].sum()

0.1610948286520987

In [283]:
district_demo_2020['black'].sum()/district_demo_2020['district_pop'].sum()

0.1592836985813933